name: C++ CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: action/checkout@v2

      - name: Install dependencies
        uses: sudo apt-get install -y g++

      - name: Run the program
        run: ./main
